name: Conseguir Licencia Manual
on: 
  push:
    branches:
      - develop
jobs:
  conseguir-licencia:
    runs-on: ubuntu-latest
    steps:
      - name: Solicitar archivo de activacion
        id: getLicense
        uses: game-ci/unity-request-activation-file@v2
        continue-on-error: true
      
      - name: Subir archivo generado
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v20XX.alf
          path: ${{ steps.getLicense.outputs.filePath }}