name: Ejecutar Tests de Unity 

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  testAllModes:
    name: Test en ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ejecutar Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          testMode: ${{ matrix.testMode }}
          artifactsPath: artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Guardar resultados
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test-Results-${{ matrix.testMode }}
          path: artifacts